version: '3'
services: 
  flask:
    build: app
    container_name: plataforma_cursos
    image: fslab/cursos
    environment: 
      DB: ${DB}
    volumes: 
      - .:/app
    depends_on:
      - db
  db:
    container_name: db_cursos
    image: mariadb:latest
    restart: always
    environment: 
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_HOST: ${DB_HOST}
      MARIADB_DATABASE: ${DB_DATABASE}
    volumes: 
      - ./data:/var/lib/mysql/
